[snips-common]
bus = "mqtt"
mqtt = "192.168.2.104:1883"
site_id = "snipshome01"
audio = ["snipshome01@mqtt"]
assistant = "/usr/share/snips/assistant"
user_dir = "/usr/share/snips"
locale = "fr-FR"
## MQTT authentication
# mqtt_username = ""
# mqtt_password = ""

[snips-audio-server]
# frame = 256
bind = "snipshome01@mqtt"
mike = "rpi"
# disable_playback = false


[snips-notify]
serial_out = "/dev/ttyUSB0"
serial_speed = 57600
pannel_height = 8
pannel_width = 16
image_directory = "/usr/share/snips/images"


[snips-home]
button_gpio_bcm = 17

mqtt_homestation = "snipshome"
mqtt_topic_presence = "home/presence"
mqtt_payload_presence = "Yes"

